name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r lambda-serverless-backend/requirements.txt

      - name: Build Docker Images
        run: |
          docker build -t lambda-python ./lambda-serverless-backend/functions/python
          docker build -t lambda-js ./lambda-serverless-backend/functions/javascript

      - name: ✅ Run Python Function Inside Docker
        run: |
          docker run --rm lambda-python arg1 arg2

      - name: ✅ Run JavaScript Function Inside Docker
        run: |
          docker run --rm lambda-js arg1 arg2

      - name: Run Python Unit Tests
        run: |
          pytest
